obs_connection:
  obs_host: 'localhost'
  obs_port: 4457
  # Leave empty if no password is set
  obs_password:

paths:
  buffer_folder: 'D:\VideoCapture\SourceRecordBuffer'
  save_folder: 'D:\VideoCapture\TestVideos'

target_machine:
  ip: '192.168.0.211'
  port: 4422

receiver_machine:
  ip: '192.168.0.180'
  port: 4422
